name: merciless_flutter_lints
version: 0.1.1
homepage:
environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=3.16.8"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: